### ISSUE TITLE
Fallback if no render object is defined for variable

### ISSUE THREAD

**Issue by oliverroick** [developmentseed/stac-explorer#23]
Question about the render extension.

In [this collection](https://github.com/developmentseed/stac-explorer/blob/main/public/stac/GPM_3IMERGDF.stac.json), we have a couple of variables:

- precipitation
- precipitation_cnt
- precipitation_cnt_cond
- MWprecipitation
- MWprecipitation_cnt
- randomError (... and some others)

And the render extension specifies:

- precipitation
- MWprecipitation
- randomError

Users select a variable to add a layer to the map, and so far I was thinking that there would be a render object for each variable. How do we want to deal with cases where is isn’t the case, eg. user selects `precipitation_cnt`?

There seem to be different options:

- In the example above, we can match the render object to the variable with `variable.startsWith(renderObjectKey)` but that feels unreliable. 
- We only show the variables that have a matching render config.
- We add a default option to the `renders`, which we can use in clients as the fallback.

**Comment by abarciauskas-bgse** [comment]
closing as completed
